name: Trigger auto deployment for containerapp covid-api-mgm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ start ]
    paths:
    - '**'
    - '.github/workflows/covid-api-mgm-AutoDeployTrigger-026e32f1-b44a-469f-88e3-cb1c827a5459.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acgclbmgm.azurecr.io
          username: ${{ secrets.COVIDAPIMGM_REGISTRY_USERNAME }}
          password: ${{ secrets.COVIDAPIMGM_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acgclbmgm.azurecr.io/covid-api-mgm:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.COVIDAPIMGM_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n covid-api-mgm -g acg-cbl-rg --server acgclbmgm.azurecr.io --username  ${{ secrets.COVIDAPIMGM_REGISTRY_USERNAME }} --password ${{ secrets.COVIDAPIMGM_REGISTRY_PASSWORD }}
            az containerapp update -n covid-api-mgm -g acg-cbl-rg --image acgclbmgm.azurecr.io/covid-api-mgm:${{ github.sha }}
